{% set name = "gladier" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gladier-{{ version }}.tar.gz
    sha256: b0754723f025d2842b2b05eacab2a933ff9bf5321819a0b9ce2734b8f4111bb1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fair-research-login >=0.2.6
    - globus-compute-sdk >=2.0.1,<3.0.0
    - globus-sdk >=3.23.0,<4
    - packaging >=21.3
    - pydantic >=1.0
    - python >=3.6

test:
  imports:
    - gladier
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/globus-gladier/gladier
  summary: An SDK for rapidly developing Globus Flows while leveraging FuncX functions.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carterbox
    - AdvancedPhotonSource/ptychodus
