{% set name = "gladier" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gladier-{{ version }}.tar.gz
    sha256: 79add4d9adff34dea5c760170bd098adfbde3c8c67014002b714d1ee83f8edf0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - fair-research-login >=0.2.6
    - globus-compute-sdk >=2.0.1,<3.0.0
    - globus-sdk >=3.23.0,<4
    - packaging >=21.3
    - pydantic >=1.0
    - python >={{ python_min }}

test:
  imports:
    - gladier
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/globus-gladier/gladier
  summary: An SDK for rapidly developing Globus Flows while leveraging FuncX functions.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carterbox
    - AdvancedPhotonSource/ptychodus
